name: Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: ssh-keyscan -H ${{ secrets.SERVER }} > ~/.ssh/known_hosts
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.14
      - uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - run: npm i
      - run: SERVER=deploy@${{ secrets.SERVER }} npm run deploy
